# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('href', models.CharField(default='', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('datetime', models.DateTimeField()),
                ('content', models.CharField(default='', max_length=1024)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
