# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20171129_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='coverimg',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
